# Generated by Django 3.1.13 on 2021-10-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num',
            field=models.IntegerField(blank=True, default=1000),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickName',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
